### ISSUE TITLE
ERROR in  command  《$ python summarise_Hbx.py --taxa <reciprocal blastoutput file> --gene <specify class of hbx gene>》

### ISSUE THREAD

**Issue by Jiahe-Sun** [PeterMulhair/HbxFinder#1]
Hello, I want to identify the HOX gene cluster in the Drosophila genome, but it failed, showing some unknown bugs in your script, I hope to get help, thank you
`$ python summarise_Hbx.py --taxa <reciprocal blastoutput file> --gene <specify class of hbx gene>

>>(base) sunjaihe@sunjaihe-A320MH:~/jupyter_notebook/HbxFinder/hbxfinder/second_search/recip_blast$ python summarise_Hbx.py --taxa genome_HOX_recipBlast.fasta --gene HOX --path /home/sunjaihe/jupyter_notebook/data/

['/home/sunjaihe/jupyter_notebook/data/fruitfly.fasta']
Traceback (most recent call last):
File "summarise_Hbx.py", line 33, in <module>
species = GCA2sp[sp_name]

`

**Comment by Jiahe-Sun** [comment]
Can you explain the input and output files of each step, there are many files generated and it is easy to get confused

**Comment by Jiahe-Sun** [comment]
Would appreciate your advice to run the Drosophila genome file and look for the HOX gene cluster, thanks a lot

**Comment by PeterMulhair** [comment]
Hi @sunjiahe-hub,

Thanks for taking interest and flagging this issue. I had updated the code and it should run without errors now (I ran it on the Drosophila genome myself and it worked ok). You will have to clone the repo again and rerun.

The current pipeline does produce many files but I am looking to make things more streamlined in the future.
The output that is most appropriate is the one found in `second_search/recip_blast/hbx_clusters/`. This will have the ordered output for your species and homeobox gene of interest. 
I notice in your code to create this file you used the incorrect input. The `--taxa` argument should be `../species_hbx/species_HOX.fasta`, where species is whatever the name of your species is.


To annotate the Drosophila Hox cluster I downloaded the Drosophila genome from ensembl.org - importantly the genome file is named so that it has the species name `Drosophila_melanogaster` followed by a `.` - this naming convention is what will be used in the output, so all genomes you wish to annotate should be named as such eg. ensembl Drosophila genome file is called `Drosophila_melanogaster.BDGP6.32.dna_sm.toplevel.fasta`

So now if you clone the repo again and with the Drosophila genome file downloaded somewhere on your device you should be able to run the pipeline as:

```
cd HbxFinder/hbxfinder/blast_search
python blast_run.py --path </path/to/genome/assemblies/>
cd recip_blast/
python recip_blast.py --infile blast_parsed_output.fasta --outfile <your output file name>
python summarise_Hbx.py --taxa <your_file_name>_hbx.fasta --gene HOX

cd HbxFinder/hbxfinder/second_search
python data_blast.py --gene HOX --path </path/to/genome/assemblies/>
cd recip_blast/
python recip_blast.py --gene HOX
python summarise_Hbx.py --taxa species_hbx/<species_name>_HOX.fasta --gene HOX --path </path/to/genome/assemblies/>
```

The output you will be interested will be in the `hbx_clusters/` directory.

Please let me know if you have any more questions about the workflow (I will work to make this more efficient and may add an example to the repo). Additionally, if you run into any issues or errors running the code let me know.

Best of luck!

**Comment by Jiahe-Sun** [comment]
Peter, I'm glad you put in the effort to handle my request, I'm struggling with how to modify your script.
 thanks again for your help! brother

**Comment by Jiahe-Sun** [comment]
Hi, peter
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;I have identified the HOX gene in Drosophila melanogaster and the results are as follows,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;I have some doubts. Only 8 hox genes have been reported in Drosophila melanogaster. What are the unpg, btn, cad, eve, exex and other genes in the results?
&gt;Drosophila_melanogaster
NW_022045832.1 2836951 2837128 Ro 98.305
NW_022045657.1 7928549 7928741 Pb 100.000
NW_022045657.1 7928907 7929045 Pb 100.000
NW_022045657.1 7963917 7964094 zen 79.310
NW_022045657.1 7974377 7974554 zen 100.000
NW_022045657.1 7979196 7979373 zen 100.000
NW_022045657.1 8009654 8009831 Dfd 100.000
NW_022045657.1 8056374 8056560 Scr 100.000
NW_022045657.1 8102449 8102626 ftz 93.220
NW_022045657.1 8144016 8144193 Antp 100.000
NW_022045657.1 8330682 8330865 Ubx 100.000
NW_022045643.1 1531053 1531230 exex 100.000
NW_022045643.1 14897392 14897569 ind 100.000
NW_022045833.1 5018620 5018797 eve 98.333
NW_022045847.1 2297921 2298053 Abd-B 100.000
NW_022045847.1 2298079 2298166 Abd-B 100.000
NW_022045847.1 2444037 2444220 abd-A 100.000
NW_022045847.1 2560747 2560912 lab 89.474
NW_022045847.1 2561230 2561437 lab 89.474
NW_022045830.1 5074579 5074756 btn 96.610
NW_022045707.1 358264 358417 unpg 100.000
NW_022045707.1 358564 358615 unpg 100.000
NW_022045709.1 12620 12671 unpg 100.000
NW_022045709.1 12818 12971 unpg 100.000
NW_022045827.1 579224 579401 cad 98.333





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PeterMulhair/HbxFinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PeterMulhair/HbxFinder] ERROR in  command  《$ python summarise_Hbx.py --taxa <reciprocal blastoutput file&gt; --gene <specify class of hbx gene&gt;》 (Issue #1)





 
Hi @sunjiahe-hub,
 
Thanks for taking interest and flagging this issue. I had updated the code and it should run without errors now (I ran it on the Drosophila genome myself and it worked ok). You will have to clone the repo again and rerun.
 
The current pipeline does produce many files but I am looking to make things more streamlined in the future.
 The output that is most appropriate is the one found in second_search/recip_blast/hbx_clusters/. This will have the ordered output for your species and homeobox gene of interest.
 I notice in your code to create this file you used the incorrect input. The --taxa argument should be ../species_hbx/species_HOX.fasta, where species is whatever the name of your species is.
 
To annotate the Drosophila Hox cluster I downloaded the Drosophila genome from ensembl.org - importantly the genome file is named so that it has the species name Drosophila_melanogaster followed by a . - this naming convention is what will be used in the output, so all genomes you wish to annotate should be named as such eg. ensembl Drosophila genome file is called Drosophila_melanogaster.BDGP6.32.dna_sm.toplevel.fasta
 
So now if you clone the repo again and with the Drosophila genome file downloaded somewhere on your device you should be able to run the pipeline as:
 cd HbxFinder/hbxfinder/blast_search python blast_run.py --path </path/to/genome/assemblies/&gt; cd recip_blast/ python recip_blast.py --infile blast_parsed_output.fasta --outfile <your output file name&gt; python summarise_Hbx.py --taxa <your_file_name&gt;_hbx.fasta --gene HOX  cd HbxFinder/hbxfinder/second_search python data_blast.py --gene HOX --path </path/to/genome/assemblies/&gt; cd recip_blast/ python recip_blast.py --gene HOX python summarise_Hbx.py --taxa species_hbx/<species_name&gt;_HOX.fasta --gene HOX --path </path/to/genome/assemblies/&gt;  
The output you will be interested will be in the hbx_clusters/ directory.
 
Please let me know if you have any more questions about the workflow (I will work to make this more efficient and may add an example to the repo). Additionally, if you run into any issues or errors running the code let me know.
 
Best of luck!

**Comment by PeterMulhair** [comment]
Hi,

Glad you got it to run ok. So the output does look pretty normal to me, the other genes are all homeobox genes from the HOXL subclass. 
You're right that the Drosophila Hox cluster comprises of 8 genes (Antp to Pb), which you can see in your output, the remaining genes are the rest of the Hox class genes, which you can ignore if it's not what you're interested in.

I hope this all makes sense.
