### ISSUE TITLE
get_seq_data.py update

### ISSUE THREAD

**Issue by luisamarins** [PeterMulhair/HbxFinder#2]
Hello and thanks for developping this very useful pipeline :)
I managed to run all the steps so far but it seems to me that the last script [get_seq_data.py](https://github.com/PeterMulhair/HbxFinder/blob/master/hbxfinder/second_search/HD_seq_out/get_seq_data.py) isn't totally compatible with the previous ones - one example: it refers to a directory named 'raw' that doesn't exist (lines 23 and 30) .

Do you happen to have an updated version of this script? this would be super helpful

Thank you!!

**Comment by PeterMulhair** [comment]
Hi Luisa,

Apologies for the delay in responding, I didn't get a notification for your issue.

I've updated the seq data script and pushed it to the repo, so you should be able to download and run. If there are any issues please do let me know and I'll try to fix it as quick as possible.

I should say that this script to the most experimental/needs more attention from me to improve it. For instant, it can't deal with introns in the homeodomain sequence, so you should check the output and make any changes manually as needed. It also requires the sixpack tool to run (which converts nucleotide to amino acid) which you can install via conda pretty easily.

Hope it all works ok!
Peter
